apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-briefings-celery-beat
  namespace: my-briefings
  labels:
    app: my-briefings-celery-beat
  annotations:
    deployment.kubernetes.io/revision: "2"
    last-updated: "2025-08-11T08:45:00Z"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-briefings-celery-beat
  template:
    metadata:
      labels:
        app: my-briefings-celery-beat
    spec:
      containers:
      - name: celery-beat
        image: my-briefings-ingestion:latest
        imagePullPolicy: Never
        workingDir: /app
        command: ["celery", "-A", "celery_app", "beat", "--loglevel=info"]
        env:
        - name: DATABASE_URL
          value: "postgresql://fastapi:password@64.227.134.87:5432/briefings_feed"
        - name: PERPLEXITY_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: perplexity-api-key
        - name: NEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: news-api-key
        - name: PYTHONPATH
          value: "/app:/app/shared"
        - name: ENABLE_POST_PROCESSING_NEWSAPI
          value: "true"
        - name: ENABLE_POST_PROCESSING_PERPLEXITY
          value: "true"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m" 