name: Deploy and Run Ingestion Service Fix

on:
  workflow_dispatch:
    inputs:
      run_fix:
        description: 'Run the ingestion service fix script'
        required: true
        default: true
        type: boolean

env:
  DROPLET_IP: ${{ secrets.DIGITALOCEAN_HOST }}
  DROPLET_USER: root
  SSH_PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

jobs:
  deploy-and-fix:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug secrets and environment
      run: |
        echo "🔍 Debugging secrets and environment..."
        echo "DROPLET_IP: $DROPLET_IP"
        echo "DROPLET_USER: $DROPLET_USER"
        echo "DROPLET_IP length: ${#DROPLET_IP}"
        echo "SSH_PRIVATE_KEY length: ${#SSH_PRIVATE_KEY}"
        
        if [ -z "$DROPLET_IP" ]; then
          echo "❌ DROPLET_IP is empty or not set"
          exit 1
        fi
        
        if [ -z "$SSH_PRIVATE_KEY" ]; then
          echo "❌ SSH_PRIVATE_KEY is empty or not set"
          exit 1
        fi
        
        echo "✅ Secrets appear to be set"
        
    - name: Setup SSH
      run: |
        echo "🔧 Setting up SSH..."
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
        echo "SSH setup complete"
        
    - name: Test SSH connection
      run: |
        echo "🔍 Testing SSH connection..."
        echo "Testing connection to $DROPLET_USER@$DROPLET_IP"
        
        # Test basic connectivity
        ping -c 3 $DROPLET_IP || echo "❌ Ping failed"
        
        # Test SSH connection (without executing commands)
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=10 $DROPLET_USER@$DROPLET_IP "echo 'SSH connection successful'" || echo "❌ SSH connection failed"
        
    - name: Check if script exists
      run: |
        echo "🔍 Checking if fix script exists..."
        ls -la fix_ingestion_service.sh || echo "❌ Script not found"
        cat fix_ingestion_service.sh | head -5 || echo "❌ Cannot read script"
        
    - name: Copy fix script to droplet
      run: |
        echo "📤 Copying fix script to droplet..."
        echo "Source: $(pwd)/fix_ingestion_service.sh"
        echo "Destination: $DROPLET_USER@$DROPLET_IP:/root/"
        
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -v fix_ingestion_service.sh $DROPLET_USER@$DROPLET_IP:/root/
        
    - name: Run fix script on droplet
      run: |
        echo "🔧 Running ingestion service fix on droplet..."
        echo "Connecting to: $DROPLET_USER@$DROPLET_IP"
        
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP << 'EOF'
          echo "🔍 Current directory: $(pwd)"
          echo "🔍 Listing files:"
          ls -la
          
          echo "🔍 Checking if script exists:"
          ls -la fix_ingestion_service.sh || echo "❌ Script not found"
          
          echo "🔍 Making script executable:"
          chmod +x fix_ingestion_service.sh
          
          echo "🔍 Running script:"
          ./fix_ingestion_service.sh
        EOF
        
    - name: Clean up script
      run: |
        echo "🧹 Cleaning up script from droplet..."
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP "rm -f /root/fix_ingestion_service.sh"
        
    - name: Verify fix results
      run: |
        echo "✅ Verifying fix results..."
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP << 'EOF'
          echo "📊 Checking pod status..."
          kubectl get pods -n my-briefings
          
          echo ""
          echo "📊 Testing ingestion service..."
          curl -s http://64.227.134.87:30101/ingestion/health | jq '.'
        EOF 