name: Deploy and Run Ingestion Service Fix

on:
  workflow_dispatch:
    inputs:
      run_fix:
        description: 'Run the ingestion service fix script'
        required: true
        default: true
        type: boolean

jobs:
  deploy-and-fix:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug secrets and environment
      run: |
        echo "🔍 Debugging secrets and environment..."
        echo "DROPLET_IP: ${{ secrets.DROPLET_IP }}"
        echo "DROPLET_USER: ${{ secrets.DROPLET_USER }}"
        echo "DROPLET_IP length: ${#DROPLET_IP}"
        echo "DROPLET_USER length: ${#DROPLET_USER}"
        
        if [ -z "${{ secrets.DROPLET_IP }}" ]; then
          echo "❌ DROPLET_IP is empty or not set"
          exit 1
        fi
        
        if [ -z "${{ secrets.DROPLET_USER }}" ]; then
          echo "❌ DROPLET_USER is empty or not set"
          exit 1
        fi
        
        echo "✅ Secrets appear to be set"
        
    - name: Test SSH connection
      run: |
        echo "🔍 Testing SSH connection..."
        echo "Testing connection to ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }}"
        
        # Test basic connectivity
        ping -c 3 ${{ secrets.DROPLET_IP }} || echo "❌ Ping failed"
        
        # Test SSH connection (without executing commands)
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "echo 'SSH connection successful'" || echo "❌ SSH connection failed"
        
    - name: Check if script exists
      run: |
        echo "🔍 Checking if fix script exists..."
        ls -la fix_ingestion_service.sh || echo "❌ Script not found"
        cat fix_ingestion_service.sh | head -5 || echo "❌ Cannot read script"
        
    - name: Copy fix script to droplet
      run: |
        echo "📤 Copying fix script to droplet..."
        echo "Source: $(pwd)/fix_ingestion_service.sh"
        echo "Destination: ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }}:/home/${{ secrets.DROPLET_USER }}/"
        
        scp -o StrictHostKeyChecking=no -v fix_ingestion_service.sh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }}:/home/${{ secrets.DROPLET_USER }}/
        
    - name: Run fix script on droplet
      run: |
        echo "🔧 Running ingestion service fix on droplet..."
        echo "Connecting to: ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }}"
        
        ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
          echo "🔍 Current directory: $(pwd)"
          echo "🔍 Listing files:"
          ls -la
          
          echo "🔍 Checking if script exists:"
          ls -la fix_ingestion_service.sh || echo "❌ Script not found"
          
          echo "🔍 Making script executable:"
          chmod +x fix_ingestion_service.sh
          
          echo "🔍 Running script:"
          ./fix_ingestion_service.sh
        EOF
        
    - name: Clean up script
      run: |
        echo "🧹 Cleaning up script from droplet..."
        ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "rm -f /home/${{ secrets.DROPLET_USER }}/fix_ingestion_service.sh"
        
    - name: Verify fix results
      run: |
        echo "✅ Verifying fix results..."
        ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
          echo "📊 Checking pod status..."
          kubectl get pods -n my-briefings
          
          echo ""
          echo "📊 Testing ingestion service..."
          curl -s http://64.227.134.87:30101/ingestion/health | jq '.'
        EOF 